### ISSUE TITLE
couldn't read from warp.jsonnet

### ISSUE THREAD

**Issue by hlzhang109** [YerevaNN/warp#3]
File "/home/hanlin/warp/allennlp/allennlp/common/params.py", line 488, in from_file
    file_dict = json.loads(evaluate_file(params_file, ext_vars=ext_vars))
  File "/home/hanlin/warp/allennlp/allennlp/commands/train.py", line 169, in train_model_from_file
    params = Params.from_file(parameter_filename, overrides)
  File "/home/hanlin/warp/allennlp/allennlp/commands/train.py", line 119, in train_model_from_args
    file_friendly_logging=args.file_friendly_logging,
  File "/home/hanlin/warp/allennlp/allennlp/commands/__init__.py", line 119, in main
    args.func(args)
  File "/home/hanlin/warp/allennlp/allennlp/__main__.py", line 34, in run
    main(prog="allennlp")
  File "/home/hanlin/warp/allennlp/allennlp/__main__.py", line 38, in <module>
    run()

**Comment by mahnerak** [comment]
Dear @hlzhang109,
Can you please share the full error traceback?

**Comment by hlzhang109** [comment]
It is a reversed version:
Traceback (most recent call last):
  File "/home/hanlin/warp/allennlp/allennlp/__main__.py", line 38, in <module>
    run()
  File "/home/hanlin/warp/allennlp/allennlp/__main__.py", line 34, in run
    main(prog="allennlp")
  File "/home/hanlin/warp/allennlp/allennlp/commands/__init__.py", line 119, in main
    args.func(args)
  File "/home/hanlin/warp/allennlp/allennlp/commands/train.py", line 119, in train_model_from_args
    file_friendly_logging=args.file_friendly_logging,
  File "/home/hanlin/warp/allennlp/allennlp/commands/train.py", line 169, in train_model_from_file
    params = Params.from_file(parameter_filename, overrides)
  File "/home/hanlin/warp/allennlp/allennlp/common/params.py", line 488, in from_file
    file_dict = json.loads(evaluate_file(params_file, ext_vars=ext_vars))
RuntimeError: STATIC ERROR: configs/warp.jsonnet:193:1: expected a comma before next field.

**Comment by mahnerak** [comment]
@hlzhang109 Thanks for pointing it out. I've fixed the configuration.
Just `git pull` and try again. Everything should be fine.

**Comment by hlzhang109** [comment]
Thanks it works
